# Generated by Django 4.1.2 on 2022-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='document_pdf',
            field=models.FileField(null=True, upload_to='', verbose_name='Document PDF'),
        ),
    ]
