# Generated by Django 4.1.2 on 2022-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_historique_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='prix',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historique',
            name='identifiant',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historique',
            name='theme_id',
            field=models.CharField(max_length=1000),
        ),
    ]
