# Generated by Django 4.1.2 on 2022-11-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_alter_historique_theme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='theme_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cours.theme', verbose_name='Titre du thème'),
            preserve_default=False,
        ),
    ]
