# Generated by Django 4.1.2 on 2022-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_alter_historique_theme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='theme_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
