# Generated by Django 4.1.2 on 2022-11-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0013_alter_historique_theme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom ')),
                ('etude', models.CharField(max_length=50, verbose_name="Niveau d'étude")),
                ('telephone', models.CharField(max_length=200, verbose_name='Numéro de telephone')),
                ('motivation', models.CharField(max_length=200, verbose_name='Vos motivations')),
                ('Date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
            },
        ),
    ]
