# Generated by Django 4.1.2 on 2022-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='motivation',
            field=models.TextField(max_length=200, verbose_name='Vos motivations'),
        ),
    ]
